/* // File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGP-tMvnseaSJpP9c8vRxGwlx5JwVWdkg',
    appId: '1:111670489665:web:d46a469142cd9931afccc0',
    messagingSenderId: '111670489665',
    projectId: 'versyll-3818e',
    authDomain: 'versyll-3818e.firebaseapp.com',
    storageBucket: 'versyll-3818e.appspot.com',
    measurementId: 'G-VCPYVGEY7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGnK5Q-dC1wr8f7o0NKaZQYnBxFFt1giE',
    appId: '1:111670489665:android:13a460ee1048bc2aafccc0',
    messagingSenderId: '111670489665',
    projectId: 'versyll-3818e',
    storageBucket: 'versyll-3818e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzJdCJQ4r4hEqRnDzC_Jpw42FWhI7VnNw',
    appId: '1:111670489665:ios:aadff22d30425f4cafccc0',
    messagingSenderId: '111670489665',
    projectId: 'versyll-3818e',
    storageBucket: 'versyll-3818e.appspot.com',
    iosClientId: '111670489665-r79pm5gbf0vv4vt14lb04jthpv2on3dk.apps.googleusercontent.com',
    iosBundleId: 'com.example.versyll',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzJdCJQ4r4hEqRnDzC_Jpw42FWhI7VnNw',
    appId: '1:111670489665:ios:aadff22d30425f4cafccc0',
    messagingSenderId: '111670489665',
    projectId: 'versyll-3818e',
    storageBucket: 'versyll-3818e.appspot.com',
    iosClientId: '111670489665-r79pm5gbf0vv4vt14lb04jthpv2on3dk.apps.googleusercontent.com',
    iosBundleId: 'com.example.versyll',
  );
}
 */